ARG ELK_VERSION

# https://www.docker.elastic.co/
FROM docker.elastic.co/logstash/logstash:${ELK_VERSION}

#ADD definitions/ /usr/share/logstash/definitions/
# Add your logstash plugins setup here
# Example: RUN logstash-plugin install logstash-filter-json
